# Code 2
- Basic Imputation for Numerical and Categorial
- Logistic Model (Balanced/ Unbalanced)

## 1/ Import Libraries

In [1]:
#CodeSection1
from google.colab import drive
drive.mount('/mntDrive')

Mounted at /mntDrive

In [2]:
#CodeSection2
import pandas as pd

## 2/ Import Data

In [6]:
#CodeSection3
train = pd.read_csv('/mntDrive/MyDrive/__DataScience/3 HR Analytics (Solo)/input/train.csv')
test = pd.read_csv('/mntDrive/MyDrive/__DataScience/3 HR Analytics (Solo)/input/test.csv')

### Check Train Data

In [7]:
#CodeSection4
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18359 entries, 0 to 18358
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             18359 non-null  int64
 1   city                    18359 non-null  object
 2   city_development_index  18359 non-null  float64
 3   gender                  14261 non-null  object
 4   relevent_experience     18359 non-null  object
 5   enrolled_university     18017 non-null  object
 6   education_level         17902 non-null  object
 7   major_discipline        15521 non-null  object
 8   experience              18300 non-null  object
 9   company_size            13580 non-null  object
 10  company_type            13320 non-null  object
 11  last_new_job            17992 non-null  object
 12  training_hours          18359 non-null  int64
 13  target                  18359 non-null  int64
dtypes: float64(1), int64(3), object(10)
memory usage: 2.0+ MB

### Check Test Data

In [8]:
#CodeSection4
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15021 entries, 0 to 15020
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             15021 non-null  int64
 1   city                    15021 non-null  object
 2   city_development_index  15021 non-null  float64
 3   gender                  11633 non-null  object
 4   relevent_experience     15021 non-null  object
 5   enrolled_university     14742 non-null  object
 6   education_level         14626 non-null  object
 7   major_discipline        12628 non-null  object
 8   experience              14977 non-null  object
 9   company_size            10970 non-null  object
 10  company_type            10691 non-null  object
 11  last_new_job            14717 non-null  object
 12  training_hours          15021 non-null  int64
dtypes: float64(1), int64(2), object(10)
memory usage: 1.5+ MB

### We Combine both Datasets to perform Missing Value Imputation

In [9]:
#CodeSection6
all_data = [train,test]

In [15]:
#CodeSection7
# Combine both using concat (with axis = 0) to check Missing Value
pd.concat([train,test],axis=0).isnull().sum()

enrollee_id                   0
city                          0
city_development_index        0
gender                     7486
relevent_experience           0
enrolled_university         621
education_level             852
major_discipline           5231
experience                  103
company_size               8830
company_type               9369
last_new_job                671
training_hours                0
target                    15021
dtype: int64

## 3/ Impute Numerical Variables
- Impute all Numerical Variables

### Variable/Feature 1

In [11]:
train.head()

   enrollee_id      city  ...  training_hours target
0        23798  city_149  ...             106      0
1        29166   city_83  ...              69      0
2           46   city_16  ...               4      0
3        18527   city_64  ...              26      0
4        21751  city_100  ...              88      1

[5 rows x 14 columns]

In [12]:
train.describe()

        enrollee_id  city_development_index  training_hours        target
count  18359.000000            18359.000000    18359.000000  18359.000000
mean   16729.360096                0.847140       65.899014      0.132088
std     9643.749725                0.110189       60.885300      0.338595
min        1.000000                0.448000        1.000000      0.000000
25%     8378.500000                0.796000       23.000000      0.000000
50%    16706.000000                0.910000       47.000000      0.000000
75%    25148.500000                0.920000       89.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

In [13]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
for dataset in all_data:
  dataset['city_development_index']=dataset['city_development_index'].fillna(train['city_development_index'].median())

### Variable/Feature 2

In [14]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
for dataset in all_data:
  dataset['training_hours']=dataset['training_hours'].fillna(train['training_hours'].median())

### Variable/Feature 3

In [ ]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
<Write your code here>

### Variable/Feature 4

In [ ]:
#CodeSection8
# Impute Feature with mean/median for both train and test - use for loop
<Write your code here>

## 4/ Impute Categorical Variables
- Impute all Numerical Variables

### Categorical Variable/Feature 1

In [23]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
for dataset in all_data:
  dataset['gender']=dataset['gender'].fillna(train['gender'].mode()[0])

### Categorical Variable/Feature 2

In [24]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
#gender	relevent_experience	enrolled_university	education_level	major_discipline	experience	company_size	company_type	last_new_job
for dataset in all_data:
  dataset['relevent_experience']=dataset['relevent_experience'].fillna(train['relevent_experience'].mode()[0])

### Categorical Variable/Feature 3

In [27]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
for dataset in all_data:
  dataset['enrolled_university']=dataset['enrolled_university'].fillna(train['enrolled_university'].mode()[0])

### Categorical Variable/Feature 4

In [28]:
#CodeSection9
# Impute Feature with mode (use [0]) for both train and test - use for loop
for dataset in all_data:
  dataset['education_level']=dataset['education_level'].fillna(train['education_level'].mode()[0])
  dataset['major_discipline']=dataset['major_discipline'].fillna(train['major_discipline'].mode()[0])
  dataset['experience']=dataset['experience'].fillna(train['experience'].mode()[0])
  dataset['company_size']=dataset['company_size'].fillna(train['company_size'].mode()[0])
  dataset['company_type']=dataset['company_type'].fillna(train['company_type'].mode()[0])
  dataset['last_new_job']=dataset['last_new_job'].fillna(train['last_new_job'].mode()[0])

## 5/ Now Re Check all of them

In [29]:
#CodeSection10
# Combine both to check Missing Value
pd.concat([train, test], axis = 0).isnull().sum()

enrollee_id                   0
city                          0
city_development_index        0
gender                        0
relevent_experience           0
enrolled_university           0
education_level               0
major_discipline              0
experience                    0
company_size                  0
company_type                  0
last_new_job                  0
training_hours                0
target                    15021
dtype: int64

## 6/ Prepare Data for Model Model

In [30]:
#CodeSection11
# Check first 5 rows of Test Dataset
test.head()

   enrollee_id      city  ...  last_new_job training_hours
0        16548   city_33  ...             1             15
1        12036   city_28  ...             1             94
2        11061  city_103  ...             1             17
3         5032  city_104  ...             2             76
4        17599   city_77  ...             2             65

[5 rows x 13 columns]

In [31]:
#CodeSection12
# Divide Data into X and y
X=train.drop(['enrollee_id','target'],axis=1)
y=train['target']

### Create Dummy Variables for  Categorical Variables

In [33]:
#CodeSection13
# Create Dummy Variables
X=pd.get_dummies(X,drop_first=True)

In [36]:
X.shape

(18359, 176)

In [34]:
#CodeSection14
# Check first 5 rows of X
X.head()

   city_development_index  training_hours  ...  last_new_job_>4  last_new_job_never
0                   0.689             106  ...                0                   0
1                   0.923              69  ...                0                   0
2                   0.910               4  ...                0                   0
3                   0.666              26  ...                0                   0
4                   0.887              88  ...                0                   0

[5 rows x 176 columns]

## 7/ Build Model

In [37]:
#CodeSection15
#Start by importing LogisticRegression 
from sklearn.linear_model import LogisticRegression

#Initialize LogisticRegression
clf = LogisticRegression(max_iter=1000)

In [38]:
#CodeSection16
# Fit Model
model = clf.fit(X,y)

### Check Accuracy of Model on Train Data

In [39]:
#CodeSection17
# Predict on Train Data and check predictions
y_pred = model.predict(X)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

### We can use a Accuracy Function from Metrics

In [53]:
test.head()

   enrollee_id      city  ...  last_new_job training_hours
0        16548   city_33  ...             1             15
1        12036   city_28  ...             1             94
2        11061  city_103  ...             1             17
3         5032  city_104  ...             2             76
4        17599   city_77  ...             2             65

[5 rows x 13 columns]

In [42]:
#CodeSection17
# Import accuracy_score 
from sklearn.metrics import accuracy_score

In [40]:
#CodeSection18
# Get Actual Predictions
y_true = train['target']

In [43]:
#CodeSection19
# Compare True values versus prediction we made
print(f" Train Accuracy : {accuracy_score(y_true, y_pred):0.1%}")

 Train Accuracy : 86.8%

## 8/ Prediction and Submission

### Predict

In [47]:
#CodeSection20
# Get X variables from the Test Dataset
X_test = test.drop(['enrollee_id'],axis=1)

In [48]:
#CodeSection21
#Covert to Dummies
X_test =pd.get_dummies(X_test,drop_first=True)

In [49]:
#CodeSection22
# Predict (Y/N) on X Variables of Test Dataset
X_test_prep = model.predict(X_test)

### Import Sample Submission

In [50]:
#CodeSection23
sample_submission = pd.read_csv('/mntDrive/MyDrive/__DataScience/3 HR Analytics (Solo)/input/sample_submission.csv')
sample_submission.head()

   enrollee_id  target
0        16548       0
1        12036       0
2        11061       0
3         5032       0
4        17599       0

### Create a Submission

In [51]:
#CodeSection24
submission = pd.DataFrame({
    'enrollee_id' : test['enrollee_id'],
    'target' : X_test_prep
})

### Export Submission File

In [52]:
#CodeSection25
submission.to_csv('/mntDrive/MyDrive/__DataScience/3 HR Analytics (Solo)/output/O2_LR_Basic_Impute.csv', index = False)

In [ ]:
# LB Accuracy : <Write your score here>